name: laga
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/diff-gaussian-rasterization_contrastive_f
    - submodules/simple-knn
    - third_party/segment-anything-langsplat
    - dearpygui
    - opencv-python
    - safetensors==0.4.2
    - open-clip-torch==2.22.0
    - joblib==1.1.0
    - "git+https://github.com/facebookresearch/pytorch3d.git"
    - matplotlib
    - hdbscan==0.8.33